language: python
sudo: false

branches:
    only:
        - master

python:
    - 3.6
    - 2.7
    - 3.5

install:
    - pip install . #no need for e since here we only want to install

script:
    - pytest
